from wazimap.data.tables import FieldTable


# Define our tables so the data API can discover them.
FieldTable(['rural or urban', 'sex', 'age in completed years'], table_per_level=False)
FieldTable(['employment activity status', 'sex'], universe='People aged 5 years and older', table_per_level=False)
FieldTable(['school attendance', 'sex'], universe='People aged 3 years and older', table_per_level=False)
FieldTable(['highest education level reached'], universe='People aged 3 years and older', table_per_level=False)
FieldTable(['main mode of human waste disposal'], universe='Households', table_per_level=False)
FieldTable(['main source of water'], universe='Households', table_per_level=False)
FieldTable(['main type of lighting fuel'], universe='Households', table_per_level=False)
FieldTable(['main type of floor material'], universe='Households', table_per_level=False)
FieldTable(['main type of wall material'], universe='Households', table_per_level=False)
FieldTable(['main type of roofing material'], universe='Households', table_per_level=False)
FieldTable(['contraceptive_use'], universe='Contraceptive_use', table_per_level=False, year=2014)
FieldTable(['contraceptive_modern_method'], universe='Contraceptive_use', table_per_level=False, year=2014)
FieldTable(['contraceptive_traditional_method'], universe='Contraceptive_use', table_per_level=False, year=2014)
FieldTable(['maternal care indicators'], universe='Maternal care indicators', table_per_level=False, year=2014)
FieldTable(['use of ipt'], universe='Maternal care indicators', table_per_level=False, year=2014)
FieldTable(['knowledge of hiv prevention methods', 'sex'], table_per_level=False, year = 2014)
FieldTable(['household possession of itn'], universe='ITN', table_per_level=False, year = 2014)
FieldTable(['household', 'users', 'itn_use'], universe='ITN', table_per_level=False, year = 2014)
FieldTable(['fertility'], table_per_level=False, year = 2014)
FieldTable(['vaccinations'], table_per_level=False, year = 2014)
FieldTable(['weight for age'], universe='Nutrition', table_per_level=False, year = 2014)
FieldTable(['height for age'], universe='Nutrition', table_per_level=False, year = 2014)
FieldTable(['weight for height'], universe='Nutrition', table_per_level=False, year = 2014)
FieldTable(['type', 'treatment'], table_per_level=False, year = 2014)
FieldTable(['treatment of children with fever'], table_per_level=False, year = 2014)
FieldTable(['protests'], table_per_level=False, year = 2014)
FieldTable(['schoolfires'], table_per_level=False, year = 2016)
FieldTable(['crimereport'], table_per_level=False, year = 2014)
FieldTable(['healthratios'], table_per_level=False, year = 2014)
